networks:
  shared: { }

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d app"]
      interval: 2s
      timeout: 1s
      retries: 5
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: app
      POSTGRES_HOST_AUTH_METHOD: trust
    networks: [ shared ]
    volumes:
      - type: bind
        source: ./.conf/postgres/postgresql.conf
        target: /etc/postgresql.conf
      - type: bind
        source: ./.conf/postgres/init
        target: /docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      - PG_URL=postgresql+asyncpg://test:test@postgres:5432/app
    env_file:
      - .env.example
    networks: [ shared ]
    ports:
      - "8000:8000"
    command: bash -c "python -m alembic upgrade head && python -m src.api"
  backend-test:
    build:
      context: .
      target: test
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PG_URL=postgresql+asyncpg://test:test@postgres:5432/app
    command: bash -c "sleep 5"
    env_file:
      - .env.example
    networks: [ shared ]
  nginx:
    image: nginx:alpine-slim
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .conf/nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [ shared ]
    depends_on:
      - backend
